### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mariusrueve** [MHH-RCUG/scrnaseq_app#2]
#### Generelles
- [x] RCUG schickt GitHub link zu scrnaseq Shiny App
- [x] Container wird Bestandteil des GitHub
- [x] Torsten erstellt das GitHub
- [ ] Download Skript fuer RDS Datei und Skript selbst sind im GitHub 

#### Plots
- [x] Speichern von allen Plots zusammen, Auswahl ueber Checkliste 
- [x] PDF und PNG
- [x] Violin Plots hinzufuegen, Ridge plots fuer raw und normalisierte Daten 
- [x] Marius schickt Funktionsaufrufe und Katrin ueberprueft, welche Daten geplottet werden
- [ ] Title der Plots mit Symbol plus Ensembl -> Katrin schickt wie es geht
- [x] Cluster in FeaturePlot labeln 

#### Visuals
- [x] „Genes“ not „Gene“, Doppelpunkte alle gleich 
- [x] X-Axis, Y-Axis besser beschreiben, default zuruecksetzbar

####  Helper page
- [x] Marius bereitet vor
- [ ] Colin, Torsten und Oliver befuellen mit Inhalt  

#### Ensembl Genelist
- [x] Hochladen einer Ensembl Genliste 

#### Timeline
- Oliver ab naechster Woche 3 Wochen Urlaub
- Katrin/AP Ende August/Anfang September Urlaub
- Marius muss vermutlich hat noch kein Enddatum 

#### Notes:
Vielleicht ändern von fluidPage auf navbarPage [Beispiel](https://github.com/gpilgrim2670/SwimMap/blob/master/app.R)
